### ISSUE TITLE
Error loading search results

### ISSUE THREAD

**Issue by alekseyBatuhtin** [tsriram/react-github-user-search#2]
Hello! I tried to see your application, but it doesn't work. Please check it when you will have free time. 

![Screenshot from 2019-09-26 13-12-09](https://user-images.githubusercontent.com/20453923/65662780-555a3180-e05f-11e9-9d36-db1dc8b82caf.png)
![Screenshot from 2019-09-26 13-12-30](https://user-images.githubusercontent.com/20453923/65662781-555a3180-e05f-11e9-9afa-14d9adfc08e5.png)

**Comment by tsriram** [comment]
@alekseyBatuhtin Thanks for reporting it. I've pushed a fix for this issue and it should work now. Let me know if you still see this issue or have any questions regarding the app.
